version: '3.6'
# Requires Docker v18.02 or higher.

################################################################
#   The DockerPHP Project                                      #
#   https://github.com/phpexpertsinc/docker-php                #
#   License: MIT                                               #
#                                                              #
#   Copyright Â© 2018 PHP Experts, Inc. <sales@phpexperts.pro>  #
#       Author: Theodore R. Smith <theodore@phpexperts.pro>    #
#      PGP Sig: 4BF826131C3487ACD28F2AD8EB24A91DD6125690       #
################################################################

services:
  web:
    image: phpexperts/web:nginx-php7.4
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/var/www
      - ./docker/web:/etc/nginx/custom
    ports:
      - 80:80

  db:
    image: postgres:9.6
    volumes:
      - /var/lib/docker/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dqgK6vR9%
      POSTGRES_DB: calendar

  redis:
    image: redis:3.2.6
    entrypoint:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --loglevel notice
