version: '2'

services:
  web:
    image: phpexperts/web:nginx-php7.2
    depends_on:
      - db
    links:
      - db
    volumes:
      - ..:/var/www

  db:
    image: postgres:9.6
    volumes:
      - /var/lib/docker/postgresql:/var/lib/postgresql

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Wqosrzcp!PGbQ2Wa5w6
      POSTGRES_DB: quickstart

  redis:
    image: redis:3.2.6
    entrypoint:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
      - --loglevel notice

